---
title: "Programming Project 2"
---

```{r}
#| echo: false
#| message: false
#| warning: false
library(tidyverse)
library(readxl)
assignments <- read_excel("assessment_schedule.xlsx") %>% 
  mutate(formatted_date = format(due_date, "%A, %B %d, %Y"))
```

Programming Projects are to be submitted to [gradescope](https://www.gradescope.com/courses/1044596).

**Due date: `r assignments %>% filter(assessment == "Programming Project 2") %>% pull(formatted_date)` at 9pm**

Credit for this programming project goes to Steven Truong, a former UGTA for CSC 110.

In this programming project you will implement a number of Python functions to print different types of burgers. Make sure you follow the provided [style guide](style.html) (you will be graded on it!). The only built-in function you can use is `print()`. You are **not** allowed to use any other built-in method or function from any Python library.

Also make sure you check the [Academic Integrity](academic-integrity.html) and [Common Gradescope Errors](gradescope-errors.html) pages.

Name the program `burgers.py`. Make sure that gradescope gives you the points for passing the test cases.

# Burger Restaurant

You are in-charge of a computer restaurant responsible for serving burgers to your customers. The restaurant menu only includes 6 types of burgers: plain, BLT, lettuce wrap, double, plain add mushroom, and double add onion. The order is taken as a string. For example, `"plain add mushroom"`.

You will be given the ingredients as text symbols, and your task is to put them together to display the burgers using those symbols, and print the burger.

## Ingredients

There are a total of 8 ingredients.

`top bun`:
<pre>
   __________________________
  /     <>            <>     \
 /  <>       <>   <>      <>  \
 \____________________________/
</pre>

`bottom bun`:
<pre>
  ____________________________
 /                            \
 \____________________________/
</pre>

`patty`:
<pre>
   __________________________
  |                          |
  |__________________________|
</pre>

`lettuce`:
<pre>
  \/^\/^\/^\/^\/^\/^\/^\/^\/^\
  \/^\/^\/^\/^\/^\/^\/^\/^\/^\
</pre>

`tomato`:
<pre>
  ()()()()()()()()()()()()()()
  |                          |
  ()()()()()()()()()()()()()()
</pre>

`bacon`:
<pre>
  ~~~~~~/\~~~~~~/\~~~~~~/\~~~
  ~~~~~~/\~~~~~~/\~~~~~~/\~~~
</pre>

`mushroom`:
<pre>
  |  (o)   (o)   (o)   (o)   |
</pre>

`onion`:
<pre>
  |  @@@   @@@   @@@   @@@   |
</pre>

## Menu

Next, we can use the ingredients above to make the six types of burgers on the menu given by the order.

For example, when the order is `"plain"`: `top bun` + `patty` + `bottom bun`
<pre>
   __________________________
  /     <>            <>     \
 /  <>       <>   <>      <>  \
 \____________________________/
   __________________________
  |                          |
  |__________________________|
  ____________________________
 /                            \
 \____________________________/
</pre>

Another example is `"BLT"`: `top bun` + `bacon` + `lettuce` + `tomato` + `bottom bun`
<pre>
   __________________________
  /     <>            <>     \
 /  <>       <>   <>      <>  \
 \____________________________/
  ~~~~~~/\~~~~~~/\~~~~~~/\~~~
  ~~~~~~/\~~~~~~/\~~~~~~/\~~~
  \/^\/^\/^\/^\/^\/^\/^\/^\/^\
  \/^\/^\/^\/^\/^\/^\/^\/^\/^\
  ()()()()()()()()()()()()()()
  |                          |
  ()()()()()()()()()()()()()()
  ____________________________
 /                            \
 \____________________________/
</pre>

We list the other four options on the menu below:

When the order is `"lettuce wrap"`:
<pre>
  \/^\/^\/^\/^\/^\/^\/^\/^\/^\
  \/^\/^\/^\/^\/^\/^\/^\/^\/^\
  ~~~~~~/\~~~~~~/\~~~~~~/\~~~
  ~~~~~~/\~~~~~~/\~~~~~~/\~~~
   __________________________
  |                          |
  |__________________________|
  ()()()()()()()()()()()()()()
  |                          |
  ()()()()()()()()()()()()()()
  \/^\/^\/^\/^\/^\/^\/^\/^\/^\
  \/^\/^\/^\/^\/^\/^\/^\/^\/^\
</pre>

When the order is `"double"`:
<pre>
   __________________________
  /     <>            <>     \
 /  <>       <>   <>      <>  \
 \____________________________/
   __________________________
  |                          |
  |__________________________|
   __________________________
  |                          |
  |__________________________|
  ____________________________
 /                            \
 \____________________________/
</pre>

When the order is `"double add onion"`:
<pre>
   __________________________
  /     <>            <>     \
 /  <>       <>   <>      <>  \
 \____________________________/
   __________________________
  |                          |
  |__________________________|
  |  @@@   @@@   @@@   @@@   |
   __________________________
  |                          |
  |__________________________|
  ____________________________
 /                            \
 \____________________________/
</pre>

When the order is `"plain add mushroom"`:
<pre>
   __________________________
  /     <>            <>     \
 /  <>       <>   <>      <>  \
 \____________________________/
  |  (o)   (o)   (o)   (o)   |
   __________________________
  |                          |
  |__________________________|
  ____________________________
 /                            \
 \____________________________/
</pre>

# Development Strategy

The `serve` function and the `main` function are already provided as below:

```{python}
#| eval: false
# All your functions are defined here

def serve(order):
    if order == "plain":
        plain()
    elif order == "blt":
        blt()
    elif order == "lettuce wrap":
        lettuce_wrap()
    elif order == "double":
        double()
    elif order == "plain add muchroom":
       plain_add_muchroom()
    elif order == "double add onion":
       double_add_onion()

if __name__ == '__main__':
    serve("double") # you may change the argument to the others
```

You need to define your own functions to print the burger based on the order. For example, after running the code above, a `double` burger should be displayed in the console. In the `main` function, you can change the argument (e.g., "double") in the `serve` function to print other burgers. 

You may also modify the code within the `serve` function. However, please ensure that its sole argument,     `order`, is restricted to one of the following values: `"plain"`, `"blt"`, `"lettuce wrap"`, `"double"`, `"plain add muchroom"`, and `"double add onion"`.

Note: Points will be deducted if your code lacks proper decomposition. For example, placing all print statements in just one or two functions without breaking down the logic appropriately.

::: {.callout-tip title="Before You Begin"}

We can use logical expressions in `if` and `elif` statements to print different things from a function:

```{python}
#| echo: true
#| eval: true
def is_positive(number):
  if number > 0:
    print("Number is positive")
  elif number < 0:
    print("Number is negative")
  elif number == 0:
    print("Number is zero")

def main():
  is_positive(10)
  is_positive(0)
  is_positive(-10)
  
main()
```
::: 

