---
title: "Short Projects Dates"
---

Short programming projects are due on the same day as programming problems. While the instructions for programming problems are on the website, instructions for short projects will be available only during our weekly 50-minute in-person lab sessions. 

The 2 lowest grade for short programming projects will be dropped at the end of the semester. There will be one lab session for you to work on a maximum of one short programming project submission you have missed.

To schedule your lab session go to [the weekly lab session spreadsheet](https://docs.google.com/spreadsheets/d/1EE8F9LxsAjmyygLGx9Mo95cF3XDvT4qNnNsVFRpWBN8/edit?usp=sharing).
You must use your UofA email address to access the form. Gmail or other email addresses will not work.
Once you sign up for a lab session, it will be the designated time for you to work on short weekly projects.

# Lab Schedule

This is for information only. 

* [Lab 01](lab01.html): Jan 21 to Jan 27 
* [Lab 02](lab02.html): Jan 28 to Feb 03  
* [Lab 03](lab03.html): Feb 04 to Feb 10 
* [Lab 04](lab04.html): Feb 11 to Feb 17 
* [Lab 05](lab05.html): Feb 18 to Feb 24 
* [Lab 06](lab06.html): Feb 25 to Mar 03 
* [Lab 07](lab07.html): Mar 04 to Mar 06, Mar 16 to Mar 17
* CATCH UP WEEK: Mar 18 to Mar 24
* [Lab 08](lab08.html): Mar 25 to Mar 31 
* [Lab 09](lab09.html): Apr 01 to Apr 07
* [Lab 10](lab10.html): Apr 08 to Apr 14
* [Lab 11](lab11.html): Apr 15 to Apr 21
* [Lab 12](lab12.html): Apr 22 to Apr 28