---
title: "More on Functions (class slides)"
format: revealjs
slide-number: true
---

# CSC 110 - More on Functions in Python

## Function Comments

-   Every function created is required to have a function comment, including main
-   Function comments are a multi-line string (as opposed to using `#` for other comments)

## Function Comments

```{python}
#| echo: true
#| eval: true
'''
Xinchen Yu
CSC110
Class Demonstration
This program has two functions: one to calculate the area of a sphere,
the other to calculate the volume of a sphere.
The main() function is called to print to the standard output the
area and volume of a sphere of radius .75
'''
def sphere_area(radius):
  '''
  This function calculates the area of a sphere of given radius.
  Args:
    radius: integer representing the radius of the sphere
  Returns:
    The float representing the area of a sphere of the given radius
  '''
  area = 4 * 3.1415 * radius**2
  return round(area, 2)

def sphere_volume(radius):
  '''
  This function calculates the volume of a sphere of given radius.
  Args:
    radius: integer representing the radius of the sphere
  Returns:
    The float representing the volume of a sphere of the given radius
  '''
  volume = (1 / 3) * sphere_area(radius) * radius
  return round(volume, 2)

def main():
  '''
  This function prints the area and volume of a sphere of radius .75.
  Args:
    None
  Returns:
    None
  '''
  r = .75
  a = sphere_area(r)
  v = sphere_volume(r)
  print(a, v)
  
main()
```

## Global vs. Local variables (scope)

-   Every variable has a scope: the region where the variable can be used or modified
-   **Local Variables** have local scope -- for example, a variable assigned inside a function can only be used or modified within that function
-   **Global Variables** have global scope -- for example, a variable delcared outside a function can be accessed or modified across multiple functions

## Global or Local?

```{python}
#| eval: false
#| echo: true
a = 10               # What are the global and local variables?
b = 5                # Is the output of the two programs the same 
                     # or different?
def sum():
  return a + b

def main():
  print(sum())
  
main()
```

vs.

```{python}
#| eval: false
#| echo: true
def sum(a, b):
  return a + b

def main():
  print(sum(10, 5))
  
main()
```

## Global vs. Local variables (scope)

-   In the previous program we wrote (volume and area of sphere), `r`, `v` and `a` are local variables within the `main()` function.
-   The variable `radius` and `area` are local within the `sphere_area(radius)` function scope.
-   The variable `radius` and `volume` are local within `sphere_volume(radius)`

## Argument vs. Parameter

-   Never set variables as global variables, pass values to functions when called
-   When a function is defined, the variables you want to pass to the function are called **parameter variables**
-   When the function is then called, the values you pass to the function are called **arguments**

## Argument or Parameter?

```{python}
#| eval: false
#| echo: true
# The parameters are a and b
def add(a, b):
    return a+b
  
# The arguments being passed through are 5 and 4
add(5, 4)
```


## Compare Functions

```{python}
#| echo: true
#| eval: true
def cook_food_one(order):
  message = "Your " + order + " is ready!"

def cook_food_two(order):
  message = "Your " + order + " is ready!"
  return message

def cook_food_three(order):
  message = "Your " + order + " is ready!"
  print(message)

def main():
  print(cook_food_one("pasta"))
  print(cook_food_two("burger"))
  print(cook_food_three("fries"))
  
main()
```

