---
title: "files (slides)"
format: revealjs
slide-number: true
df-print: kable
---


## Key Concepts

-   iterating a string/list/dictionary (+ if statements)

    - while loop, for loops (two ways, difference?)
    
    -   draw a loop table

-   purpose of iterating, for example:

    -   mutate (list/dictionary methods)
    
    -   aggregate (e.g., sum, factorial)
    
    -   get max or min
    
    -   concatenate strings (string methods)

# CSc 110 - files

## Files and file systems

-   On (at least most of) our computers, there is a **file system** via which we can create, save, modify, and remove files

    -   On Mac: can browse with Finder

    -   On Windows: can browse with windows explorer

-   File systems are often hierarchical

## Opening a file

-   To open a file in a python program:

    **`info = open(file_name, mode)`**

-   `file_name`: the name of the file to open

    -   It can also be a path

-   `mode`: the mode in which to open in

    -   **'a'    'r'    'w'**

## Absolute vs Relative path

    
- An **absolute path** describes the location from the root directory. 

  -   */home/doc/example.txt*

- A **relative** path describes the location of a file relative to the current (working) directory.

  -   if `.py` and `example.txt` are in the same folder, the relative path is the filename itself - *example.txt*

## Opening and closing a file

info.txt

```{html}
The quick brown fox
jumped over
the lazy
bear
sitting by the tree
```

read_file.py

```{python}
#| eval: true
#| echo: true
info = open('info.txt', 'r')
info.close()
```

## Reading a line

Use `info` object and call `readline()`to read a line

read_file.py

```{python}
#| eval: true
#| echo: true
info = open('info.txt', 'r')
line = info.readline()
info.close()

print(line)
assert line == "The quick brown fox\n"
```

## Reading three lines 

```{python}
#| eval: true
#| echo: true
info = open('info.txt', 'r')
print(info.readline())
print(info.readline())
print(info.readline())
info.close()
```

## Write a function

Function name `read_first_line`: given a `filename` string, open file in read (`'r'`) mode, read one line, close file, return that line.

Name your file `first_read.py` and submit to gradescope.

```{python}
#| eval: false
#| echo: true
assert read_first_line('info.txt') == "The quick brown fox\n"
```

## Reading a line example

info.txt

```{html}
The quick brown fox
jumped over
the lazy
bear
sitting by the tree
```

first_read.py

```{python}
#| eval: true
#| echo: true
def read_first_line(filename):
  info = open(filename, 'r')
  line = info.readline()
  info.close()
  return line

assert read_first_line('info.txt') == "The quick brown fox\n"
```

## Reading lines

-   **`file.readline()`**

    -   reads one line from a file, returns a string 

-   **`file.readlines()`**

    -   reads all of the lines, returns a list of strings

-   **`file.read()`**

    -   returns one string


## Iterating over a file 

`info` is iterable, so we can use `for x in file`:

```{python}
#| eval: true
#| echo: true
info = open('info.txt', 'r')
for line in info:
    print(line)
info.close()
```

## More string methods

We worked with `.isnumeric()`, a string method to check if a string contains only digit characters

Here are some other useful string methods:

-   `string.strip(chars)` -- removes any of the characters in chars from the beginning or end of string, returns a string
-   `string.split(chars)` -- splits string at the chars, returns a list

## More string methods

`.strip()` and `.split(" ")`
```{python}
#| eval: true
#| echo: true
info = open('info.txt', 'r')

line = info.readline()
print(line)

line = line.strip("\n")
print(line)

words = line.split(" ")
print(words)

info.close()
```

## Write your code

Use `.strip()` and `.split(" ")` to print a list: `['The', 'quick', 'brown', 'fox']`

```{python}
#| eval: false
#| echo: true
name = "The-quick-brown-fox$"
```


## More string methods

Use only `.strip()`:
```{python}
#| eval: true
#| echo: true
name = "The-quick-brown-fox$"

print(name.strip('$'))
```

Use `.strip()` and `.split(" ")`:
```{python}
#| eval: true
#| echo: true
name = "The-quick-brown-fox$"

print(name.strip('$').split('-'))
```


## Write a function

It takes a string `file_name` as argument and returns a dictionary with word counts.

Use `str.lower()` to convert a string to lowercase. 

Test case:

```{python}
#| eval: false
#| echo: true
assert count_words("info.txt") == {"the": 3, "quick": 1, "brown": 1,
                                   "fox": 1 , "jumped": 1, "over": 1, 
                                   "lazy": 1, "bear": 1, "sitting": 1,
                                   "by": 1, "tree": 1}
```

## Write a function -- solution

```{python}
#| eval: true
#| echo: true
def count_words(file_name):
  f = open(file_name, "r")
  counts = {}
  for line in f:
    words = line.strip("\n").split(" ")
    for w in words:
      lower_case_w = w.lower()
      if lower_case_w not in counts:
        counts[lower_case_w] = 1
      else:
        counts[lower_case_w] += 1
  return counts

def main():
  assert count_words("info.txt") == {"the": 3, "quick": 1, "brown": 1,
                                     "fox": 1 , "jumped": 1, "over": 1, 
                                     "lazy": 1, "bear": 1, "sitting": 1,
                                     "by": 1, "tree": 1}
                                 
main()
```

