---
title: "loops + strings (slides)"
format: revealjs
slide-number: true
---

# CSc 110 - looping through strings
  
# String Manipulation

## String indexing

-   Strings are sequences in Python
-   We can retrieve values in a sequence using `[ ]`

```{python}
#| echo: true
#| eval: true
name = "Xinchen"
name[0]
```

Note that the first index in a sequence is always `zero`.

## String indexing

Since the first index of a sequence is `zero`, the last index is going to be the length of the string `minus 1`

```{python}
#| echo: true
#| eval: true
name = "Xinchen"
len(name)
```

```{python}
#| echo: true
#| eval: true
name = "Xinchen"
name[6]
```

```{python}
#| echo: true
#| eval: false
name = "Xinchen"
name[7] # this will throw an error
```


## `in` operator

The `in` operator determines whether a given value is a constituent element of a sequence (such as a string)

```{python}
#| eval: true
#| echo: true
"i" in "aeiou"
```


```{python}
#| eval: true
#| echo: true
"eio" in "aeiou"
```

```{python}
#| eval: true
#| echo: true
not "b" in "aeiou"
```

```{python}
#| eval: true
#| echo: true
"0" in  "0987654321."
```

```{python}
#| eval: true
#| echo: true
"10.0" in  "0987654321."
```

## Write a function

Write a function `count_nondigits` to return the number of characters that are not digits (0-9) in a string.

```{python}
#| echo: true
#| eval: false
assert count_nondigits("BladeRunner2049") == 11
assert count_nondigits("2049") == 0
assert count_nondigits("abc0123") == 3
```


## Write a function - solution

```{python}
#| eval: true
#| echo: true
def count_nondigits(string):
  index = 0
  count = 0
  while index < len(string):
    if string[index] not in "0123456789":
      count += 1
    index += 1
  return count

def main():
  assert count_nondigits("BladeRunner2049") == 11
  assert count_nondigits("2049") == 0
  assert count_nondigits("abc0123") == 3
  
main()
```

## Question

How to check if a string can be converted to an integer or float? 

Can we use the string method`.isnumeric()`?

```{python}
#| eval: true
#| echo: true
user_input = "BladeRunner2049"
user_input.isnumeric()
```

```{python}
#| eval: true
#| echo: true
user_input = "2049"
user_input.isnumeric()
```

```{python}
#| eval: true
#| echo: true
user_input = "12.5"
user_input.isnumeric()
```



## Write a function

Function name `is_numeric` that takes one `string` argument of any length (assume length > 0).

It returns `True` if every character in the argument is a digit (0-9) or a period (.), `False` otherwise.

Use `in` operator instead of built-in function `isnumeric()`.

```{python}
#| echo: true
#| eval: false
assert is_numeric("BladeRunner2049") == False
assert is_numeric("2049") == True
assert is_numeric("12.5") == True
assert is_numeric("1.2.5") == False
```


## `is_numeric()` -- solution 

```{python}
#| eval: true
#| echo: true
def is_numeric(my_string):
  index = 0
  count_period = 0
  while index < len(my_string):
    if my_string[index] == ".":
      count_period += 1
    if my_string[index] not in "0123456789." or count_period > 1:
      return False
    index += 1
  return True

def main():
  assert is_numeric("234") == True
  assert is_numeric("abc") == False
  assert is_numeric("12c") ==  False
  assert is_numeric("12.3") == True
  assert is_numeric("1.2.3") == False
  
main()
```

